// search
export const SET_SHOW_SEARCH_ICON = 'SET_SHOW_SEARCH_ICON';
export const CLEAR_SEARCH_INPUT_TEXT = 'CLEAR_SEARCH_INPUT_TEXT';
// orders
export const SET_ORDER_LIST = 'SET_ORDER_LIST';
// favorites
export const GET_FAVORITES_LIST = 'GET_FAVORITES_LIST';
export const LOADING_FAVORITES_LIST = 'LOADING_FAVORITES_LIST';
// modals
export const SHOW_SORT_MODAL = 'SHOW_SORT_MODAL';
