// auth
export const IS_SENDED_CODE = 'IS_SENDED_CODE';
export const IS_AUTH_USER = 'IS_AUTH_USER';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
// search
export const SET_SHOW_SEARCH_ICON = 'SET_SHOW_SEARCH_ICON';
export const CLEAR_SEARCH_INPUT_TEXT = 'CLEAR_SEARCH_INPUT_TEXT';
export const SET_ORDERING_ADDRESS_TERM = 'SET_ORDERING_ADDRESS_TERM';
// orders
export const SET_ORDER_LIST = 'SET_ORDER_LIST';
export const CHANGE_ORDER_ADDRESS = 'CHANGE_ORDER_ADDRESS';
export const GET_ORDER_PICKUP_ADDRESSES = 'GET_ORDER_PICKUP_ADDRESSES';
// favorites
export const GET_FAVORITES_LIST = 'GET_FAVORITES_LIST';
export const LOADING_FAVORITES_LIST = 'LOADING_FAVORITES_LIST';
// modals
export const SHOW_SORT_MODAL = 'SHOW_SORT_MODAL';
// catalog block layout
export const SET_CATALOG_LAYOUT = 'SET_CATALOG_LAYOUT';
// categories
export const GET_CATEGORIES_LIST = 'GET_CATEGORIES_LIST';
export const LOADING_CATEGORIES_LIST = 'LOADING_CATEGORIES_LIST';
export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
// products
export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';
export const LOADING_PRODUCTS_LIST = 'LOADING_PRODUCTS_LIST';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const LOADING_PRODUCT_BY_ID = 'LOADING_PRODUCT_BY_ID';
export const GET_SEARCH_PRODUCTS_LIST = 'GET_SEARCH_PRODUCTS_LIST';
export const LOADING_SEARCH_PRODUCTS_LIST = 'LOADING_SEARCH_PRODUCTS_LIST';
export const UPDATE_SEARCH_PRODUCTS_TERM = 'UPDATE_SEARCH_PRODUCTS_TERM';
export const UPDATE_SORT_PRODUCTS_ORDER = 'UPDATE_SORT_PRODUCTS_ORDER';
export const GET_PRODUCTS_WITH_STOCKS_LIST = 'GET_PRODUCTS_WITH_STOCKS_LIST';
export const SET_PRODUCT_PRICE_DIF = 'SET_PRODUCT_PRICE_DIF';
export const GET_RECOMMEND_PRODUCTS_LIST = 'GET_RECOMMEND_PRODUCTS_LIST';
// localization
export const SWITH_APP_LANGUAGE = 'SWITH_APP_LANGUAGE';
// promos
export const GET_PROMOS_LIST = 'GET_PROMOS_LIST';
